import Head from 'next/head'
// import {
//   getNewProductList,
//   getSellingProductList,
//   getCategoryProduct,
//   getPromotion,
// } from './homepage/apiHomePage'
// import SectionPromotion from './homepage/parts/sectionPromotion'
// import SectionNewProducts from './homepage/parts/sectionNewProducts'
// import SectionSellingProducts from './homepage/parts/sectionSellingProducts'
// import SectionPreOrderProducts from './homepage/parts/sectionPreOrderProducts'
// import SectionFlashSellProducts from './homepage/parts/sectionFlashSellProducts'
// import SectionCategoryProduct from './homepage/parts/sectionCategoryProduct'

// layout
import type { ReactElement } from 'react'
import NestedLayout from 'src/layout/nestedLayout'
import type { NextPageWithLayout } from 'pages/_app.page'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>VEPE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Dashboard</div>
      {/* <SectionPromotion dataPromotion={dataPromotion} />
      <SectionFlashSellProducts dataNewProduct={dataNewProduct} />
      <SectionNewProducts dataNewProduct={dataNewProduct} />
      <SectionSellingProducts dataSellingProduct={dataSellingProduct} />
      <SectionPreOrderProducts dataNewProduct={dataNewProduct} />
      <SectionCategoryProduct dataCategoryProduct={dataCategoryProduct} /> */}
    </>
  )
}

// export async function getStaticProps() {
//   const dataNewProduct = await getNewProductList()
//     .then((res) => {
//       const data = res.data
//       return data
//     })
//     .catch((error) => {
//       const errors = error.response ? error.response.data : true
//       return errors
//     })
//   const dataSellingProduct = await getSellingProductList()
//     .then((res) => {
//       const data = res.data
//       return data
//     })
//     .catch((error) => {
//       const errors = error.response ? error.response.data : true
//       return errors
//     })

//   // category
//   const dataCategoryProduct = await getCategoryProduct()
//     .then((res) => {
//       const data = res.data
//       return data
//     })
//     .catch((error) => {
//       const errors = error.response ? error.response.data : true
//       return errors
//     })

//   // Promotion
//   const dataPromotion = await getPromotion()
//     .then((res) => {
//       const data = res.data
//       return data
//     })
//     .catch((error) => {
//       const errors = error.response ? error.response.data : true
//       return errors
//     })

//   return {
//     props: {
//       dataPromotion: dataPromotion,
//       dataNewProduct: dataNewProduct,
//       dataSellingProduct: dataSellingProduct,
//       dataCategoryProduct: dataCategoryProduct,
//     },
//   }
// }

Home.getLayout = function getLayout(page: ReactElement) {
  return <NestedLayout>{page}</NestedLayout>
}
export default Home
